In [1]:
import pathlib

import numpy as np
import pandas as pd
import pyarrow as pa
import swifter  # noqa: F401

from pyarrow import parquet as pq
from rdkit import Chem
from tqdm.auto import tqdm

In [ ]:
output_file = "quantumpioneer_transition_state_semiempirical_results.parquet"

In [3]:
cwd = pathlib.Path().absolute()
quantum_green = pathlib.Path("/home/shared/projects/quantum_green")
paquets = quantum_green / "supercloud_xfer"
data_dir = cwd.parent.parent / "data" / "qm_results"

In [4]:
pd.set_option("display.max_columns", None)


def head(df, n=2):
    display(df.head(n))
    print(f"Contains {len(df)} rows")


def swifter_apply(seris, func, desc="Applying function"):
    return seris.swifter.progress_bar(True, desc=desc).apply(func)


def extract_last(lst):
    if isinstance(lst, list) and len(lst) > 0:
        return lst[-1]
    return lst

In [5]:
ts_data = pd.read_pickle(quantum_green / "ts" / "quantum_green_ts_data_24july2c.pkl")
head(ts_data)

,ts_dft_log_source_utf_8_sha512,dft_table_id,ts_dft_log_path,ts_dft_route_section,charge,multiplicity,ts_dft_opt_max_steps,ts_dft_opt_normal_termination_check,ts_dft_opt_cpu_time,ts_dft_opt_wall_time,ts_dft_sum_of_electronic_and_thermal_enthalpies_hartree,ts_dft_hartreefock_energy_hartree,ts_dft_zpe_hartree,ts_dft_e0_zpe_hartree,ts_dft_gibbs_hartree,ts_dft_scf_hartree,ts_dft_frequency_modes,ts_dft_std_forces,ts_dft_opted_std_xyz,ts_dft_opted_xyz_input_orientation,is_ts,batch_label,ts_dft_log_filename_id,rsmi,psmi,r1smi,r2smi,p1smi,p2smi,r1nasmi,r2nasmi,p1nasmi,p2nasmi,std_xyz_str,xyz_str,p1_reaction_center_atom_map_num,r1_reaction_center_atom_map_num,h_atom_map_num,r1_matched_sha512,r2_matched_sha512,p1_matched_sha512,p2_matched_sha512,r1_matched_smi,r1_matched_std_xyz_str,r2_matched_smi,r2_matched_std_xyz_str,p1_matched_smi,p1_matched_std_xyz_str,p2_matched_smi,p2_matched_std_xyz_str,connectivity_check_r1,connectivity_check_r2,connectivity_check_r1_dist,connectivity_check_r2_dist,r2_h_idx,r2_reacting_site_idx,r2_reacting_site_element,r2_reacting_site_h_bond_distance,r2_ts_reacting_site_h_bond_distance,r2_ts_reacting_site_h_bond_distance_pct_change,connectivity_check_p1,connectivity_check_p2,connectivity_check_p1_dist,connectivity_check_p2_dist,p2_h_idx,p2_reacting_site_idx,p2_reacting_site_element,p2_reacting_site_h_bond_distance,p2_ts_reacting_site_h_bond_distance,p2_ts_reacting_site_h_bond_distance_pct_change,rxn_smi,fingerprint,rxn_smi_original_order,rdmc_large_factor,rdmc_small_factor,neg_freq,neg_freq_z_score,rp_connectivity_check_true_sum,connectivity_check_r1_score,connectivity_check_r2_score,connectivity_check_p2_score,connectivity_check_p1_score,ho2_ts_h_mode,ho2_non_react_h_mode,ho2_ts_h_score,ho2_non_react_h_score,ho2_non_div_ts_mode_ratio,r1_dft_e0_zpe_hartree,r2_dft_e0_zpe_hartree,p1_dft_e0_zpe_hartree,p2_dft_e0_zpe_hartree,rcomplex_dft_e0_zpe_hartree,pcomplex_dft_e0_zpe_hartree,dft_fwd_barrier_e0_zpe_hartree,dft_rev_barrier_e0_zpe_hartree,dft_fwd_Hrxn_e0_zpe_hartree,dft_fwd_barrier_e0_zpe_kcal,dft_rev_barrier_e0_zpe_kcal,dft_fwd_Hrxn_e0_zpe_kcal,ts_dlpno_log_filename_id,ts_dlpno_xyz_tuple,ts_dlpno_log_path,ts_dlpno_sp_hartree,dft_opted_xyz_tuple_used_for_dlpno_calc,r1_dlpno_sp_hartree,r2_dlpno_sp_hartree,p1_dlpno_sp_hartree,p2_dlpno_sp_hartree,all_species_has_dlpno_sp,fwd_Hrxn_dlpno_sp_hartree,ts_and_species_has_dlpno_sp,fwd_barrier_dlpno_sp_hartree,rev_barrier_dlpno_sp_hartree,fwd_Hrxn_dlpno_sp_kcal,fwd_barrier_dlpno_sp_kcal,rev_barrier_dlpno_sp_kcal,r1_dft_log_path,r2_dft_log_path,p1_dft_log_path,p2_dft_log_path,r1_dlpno_log_path,r2_dlpno_log_path,p1_dlpno_log_path,p2_dlpno_log_path,r1_dft_hartreefock_energy_hartree,r2_dft_hartreefock_energy_hartree,p1_dft_hartreefock_energy_hartree,p2_dft_hartreefock_energy_hartree,r1_dft_zpe_hartree,r2_dft_zpe_hartree,p1_dft_zpe_hartree,p2_dft_zpe_hartree,ts_and_species_has_dft_zpe,species_has_dft_zpe,fwd_Hrxn_dft_zpe_hartree,fwd_barrier_dft_zpe_hartree,rev_barrier_dft_zpe_hartree,fwd_Hrxn_dlpno_sp_dft_zpe_hartree,fwd_barrier_dlpno_sp_dft_zpe_hartree,rev_barrier_dlpno_sp_dft_zpe_hartree,fwd_Hrxn_dlpno_sp_dft_zpe_kcal,fwd_barrier_dlpno_sp_dft_zpe_kcal,rev_barrier_dlpno_sp_dft_zpe_kcal,r1_dft_zpe_scaled_hartree,r2_dft_zpe_scaled_hartree,p1_dft_zpe_scaled_hartree,p2_dft_zpe_scaled_hartree,ts_dft_zpe_scaled_hartree,fwd_barrier_dlpno_sp_dft_zpe_scaled_hartree,rev_barrier_dlpno_sp_dft_zpe_scaled_hartree,fwd_Hrxn_dlpno_sp_dft_zpe_scaled_hartree,rev_Hrxn_dlpno_sp_dft_zpe_scaled_hartree,fwd_barrier_dlpno_sp_dft_zpe_scaled_kcal,rev_barrier_dlpno_sp_dft_zpe_scaled_kcal,fwd_Hrxn_dlpno_sp_dft_zpe_scaled_kcal,rev_Hrxn_dlpno_sp_dft_zpe_scaled_kcal,ts_dft_frequencies,r1_dft_frequencies,r2_dft_frequencies,p1_dft_frequencies,p2_dft_frequencies,smiles
0,4c648a435eb66f655a9afa7aebe1b6288cfbe5d4377ab7...,545983,/home/gridsan/groups/RMG/Projects/Habs/data/ts...,"P opt=(ts,calcall,maxcycle=64,noeig,nomicro,ca...",0,2,64,True,53637.5,1178.8,-499.312919,-499.513846,0.187656,-499.326190,-499.365824,499.513846,"[[[1.0, 8.0, -0.01, 0.0, -0.03], [2.0, 8.0, 0....","[[1.0, 8.0, 2.5425e-05, -7.272e-06, -2.4919e-0...","[[1.0, 8.0, 0.0, -0.296608, 2.50034, -0.42834]...","[[1.0, 8.0, 0.0, -0.07876, -1.01869, -0.072806...",True,oo_g4mp2,2584189,[O:1]([O:2])[H:3].[C:4]1([C:5]([C:8]([C:10](=[...,[C:4]1([C:5]([C:8]([C:10](=[O:22])[H:23])([H:1...,[O:1]([O:2])[H:3],[C:4]1([C:5]([C:8]([C:10](=[O:22])[H:23])([H:1...,[C:4]1([C:5]([C:8]([C:10](=[O:22])[H:23])([H:1...,[O:1]([O:2][H:11])[H:3],[O]O,CC(CC=O)C1CC1,C[C](CC=O)C1CC1,OO,23\n\nO -0.296608 2.50034 -0.42834\nO 0.12862 ...,23\n\nO -0.07876 -1.01869 -0.072806\nO 0.9303 ...,5,2,11,d1ca3ead22026cd95cd9eba36a347437a7d6f6adab5c4b...,610ba260b0107be2c50383d2bf26bf5fc5467c7ad8288b...,0a477b232ce026d015e750e1199a52b816a5fd4e81b88d...,a378723d20b8e233b8c52a4a265f23e51eed6de0c99f59...,[O:1][O:2][H:3],3\n\nO 0.055113 0.705073 0.0\nO 0.055113 -0.59...,[C:1]([C:2]([C:3]([C:4](=[O:5])[H:15])([H:13])...,20\n\nC 0.216362 1.782055 0.054566\nC -0.13150...,[C:1]([C:2]([C:3]([C:4](=[O:5])[H:14])([H:12])...,19\n\nC -0.008753 1.669215 -0.212931\nC 0.0510...,[O:1]([O:2][H:4])[H:3],4\n\nO 0.0 0.708624 -0.054351\nO -0.0 -0.70862...,True,True,[0.05700816 0.05700816 0.00748912 0.00748912],[0.00946447 0.00248608 0.00129841 0.00037547 0...,11,1,C,1.106773,1.312754,0.156907,True,True,[1.36928176e-02 2.58629462e-03 6.66837529e-03 ...,[0.02934109 0.00283253 0.02934109 0.00283253],3,1,O,0.965842,1.209684,0.201575,[O:1]([O:2])[H:3].[C:4]1([C:5]([C:8]([C:10](=[...,45ff0c52c5e6de887c3d5db1a3d4530d,[C:4]1([C:5]([C:8]([C:10](=[O:22])[H:23])([H:1...,13.648967,0.0,-1819.2074,-0.180464,4,0.218532,0.013364,0.057661,0.029017,"[11.0, 1.0, 0.05, 0.99, 0.03]","[1.0, 8.0, -0.01, 0.0, -0.03]",0.991716,0.031623,0.031887,-150.721953,-348.624311,-347.977987,-151.349014,-499.346264,-499.327001,0.020074,0.000811,0.019263,12.596625,0.508910,12.087715,id54674,"((-0.07876, -1.01869, -0.072806), (0.9303, -0....",/home/gridsan/jburns/RMG_shared/Projects/Hao-W...,-499.420713,"((-0.07876, -1.01869, -0.072806), (0.9303, -0....",-150.773531,-348.675816,-348.013214,-151.4225,True,0.013633,True,0.028633,0.015001,8.554567,17.967630,9.413063,/home/gridsan/groups/RMG/Projects/Hao-Wei-Osca...,/home/gridsan/groups/RMG/Projects/Hao-Wei-Osca...,/home/gridsan/groups/RMG/Projects/Hao-Wei-Osca...,/home/gridsan/groups/RMG/Projects/Hao-Wei-Osca...,/home/gridsan/jburns/RMG_shared/Projects/Hao-W...,/home/gridsan/jburns/RMG_shared/Projects/Hao-W...,/home/gridsan/jburns/RMG_shared/Projects/Hao-W...,/home/gridsan/jburns/RMG_shared/Projects/Hao-W...,-150.736553,-348.800739,-348.140437,-151.376196,0.0146,0.176428,0.16245,0.027182,True,True,-0.001396,-0.003372,-0.001976,0.012236,0.025261,0.013025,7.678501,15.851793,8.173292,0.014197,0.171556,0.157964,0.026431,0.182474,0.025355,0.01308,0.012275,-0.012275,15.910219,8.207526,7.702692,-7.702692,"[-1819.2074, 54.014, 69.9409, 78.7383, 95.0168...","[1268.6637, 1466.9774, 3673.0462]","[54.4468, 75.2434, 102.0769, 166.2486, 229.237...","[38.6623, 46.6427, 70.6254, 124.3627, 195.2907...","[355.51, 1029.1913, 1349.894, 1491.2134, 3851....",[O:1]([O:2])[H:3].[C:4]1([C:5]([C:8]([C:10](=[...
1,3fcdf61497a20d2e765655162f9a50bd8067a6ae90e90e...,545984,/home/gridsan/groups/RMG/Projects/Habs/data/ts...,"P opt=(ts,calcall,maxcycle=64,noeig,nomicro,ca...",0,2,64,True,87382.4,1915.1,-575.604651,-575.835651,0.216399,-575.619252,-575.662671,575.835651,"[[[1.0, 8.0, 0.02, 0.01, -0.01], [2.0, 8.0, -0...","[[1.0, 8.0, -6.29e-07, -8.11e-07, 6.03e-07], [...","[[1.0, 8.0, 0.0, 2.669129, -1.916241, 0.102074...","[[1.0, 8.0, 0.0, 2.900762, 1.051554, -2.878215...",True,oo_g4mp2,2759514,[O:1]([O:2])[H:3].[C:4]1([O:11][C:5]([C:8]([O:...,[C:4]1([O:11][C:5]([C:8]([O:12][C:10]([H:25])[...,[O:1]([O:2])[H:3],[C:4]1([O:11][C:5]([C:8]([O:12][C:10]([H:24])(...,[C:4]1([O:11][C:5]([C:8]([O:12][C:10]([H:25])[...,[O:1]([O:2][H:24])[H:3],[O]O,COCC(C)OC1CC1,[CH2]OCC(C)OC1CC1,OO,26\n\nO 2.669129 -1.916241 0.102074\nO 3.62579...,26\n\nO 2.900762 1.051554 -2.878215\nO 3.37906...,10,2,24,d1ca3ead22026cd95cd9eba36a347437a7d6f6adab5c4b...,09d7101d699a76511a92cf2607786664c9f074ee20a378...,36ef1974554666d88c201c7fd525e42cbdfc9e88e4f93e...,a378723d20b8e233b8c52a4a265f23e51eed6de0c99f59...,[O:1][O:2][H:3],3\n\nO 0.055113 0.705073 0.0\nO 0.055113 -0.59...,[C:1]([O:2][C:3]([C:4]([C:5]([H:16])([H:17])[H...,23\n\nC 2.355263 -1.592675 0.183484\nO 2.52464...,[C:1]([O:2][C:3]([C:4]([C:5]([H:15])([H:16])[H...,22\n\nC 1.79229 -1.9024 0.57597\nO 1.564071 -1...,[O:1]([O:2][H:4])[H:3],4\n\nO 0.0 0.708624 -0.054351\nO -0.0 -0.70862...,True,True,[0.05822702 0.05822702 0.00820458 0.00820458],[3.06791240e-02 3.36613486e-03 3.69001136e-03 ...,9,0,C,1.099011,1.332498,0.175225,True,True,[0.00805211 0.00649287 0.00520663 0.00805211 0...,[0.02822179 0.00210964 0.02822179 0.00210964],3,1,O,0.965842,1.200348,0.195365,[O:1]([O:2])[H:3].[C:4]1([O:11][C:5]([C:8]([O:...,fe6f921ca72c34388a0ece88ef9c4bf1,[C:4]1([O:11][C:5]([C:8]([O:12][C:10]([H:24])(...,15.512329,0.0,-1780.9655,0.010284,4,0.228270,0.069623,0.053246,0.010703,"[24.0, 1.0, -0.34, 0.92, 0.13]","[1.0, 8.0, 0.02, 0.01, -0.01]",0.989394,0.024495,0.024757,-150.721953,-424.919453,-424.271413,-151.349014,-575.641406,-575.620427,0.022154,0.001175,0.020979,13.901845,0.737324,13.164521,id55203,"((2.900762, 1.051554, -2.878215), (3.379065, 0...",/home/gridsan/jburns/RMG_shared/Projects/Hao-W...,-575.755980,"((2.900762, 1.051554, -2.878215), (3.379065, 0...",-150.773531,-425.012518,-424.350164,-151.4225,True,0.013386,True,0.030069,0.016683,8.399621,18.868576,10.468954,/home/gridsan/groups/RMG/Projects/Hao-Wei-Osca...,/home/gridsan/groups/RMG/Projects/Hao-Wei-Osca...,/home/gridsan/groups/RMG/Projects/Hao-Wei-Osca...,/home/gridsan/groups/RMG/Projects/Hao-Wei-Osca...,/home/gridsan/jburns/RMG_shared/Projects/Hao-W...,/home/gridsan/jburns/RMG_shared/Projects/Hao-W...,/home/gridsan/jburns/RMG_shared/Projects/Hao-W...,/home/gridsan/jburns/RMG_shared/Projects/Hao-W...,-150.736553,-425.124273,-424.462568,-151.376196,0.0146,0.204819,0.191155,0.027182,True,True,-0.001083,-0.003021,-0.001938,0.012303,0.027048,0.014746,7.720091,16.973058,9.252967,0.014197,0.199164,0.185876,0.026431,0.210423,0.027132,0.014799,0.012333,-0.012333,17.0254,9.286544,7.738855,-7.738855,"[-1780.9655, 22.7631, 39.1821, 48.2943, 53.310...","[1268.6637, 1466.9774, 3673.0462]","[41.7173, 46.7835, 79.0284, 116.919, 165.6573,...","[41.6898, 69.9592, 110.6483, 138.1279, 181.957...","[355.51, 1029.1913, 1349.894, 1491.2134, 3851....",[O:1]([O:2])[H:3].[C:4]1([O:11][C:5]([C:8]([O:...

Contains 167237 rows

In [6]:
matching_df = pd.read_csv(cwd / "quantum_green_ts_data_match.csv")
matching_df["semiempirical_index"] = np.where(
    matching_df["xtb_index"] >= 0,
    matching_df["xtb_index"],
    np.where(
        matching_df["pm7_index"] >= 0,
        matching_df["pm7_index"],
        matching_df["am1_index"],
    ),
)
matching_df = (
    matching_df[matching_df["semiempirical_index"] >= 0]
    .sort_values("semiempirical_index")
    .reset_index(drop=True)
    .copy()
)
matching_df["smiles"] = matching_df["dft_table_id"].map(
    ts_data.set_index("dft_table_id")["smiles"]
)
head(matching_df)

,dft_table_id,dft_index,dlpno_index,am1_index,pm7_index,xtb_index,semiempirical_index,smiles
0,494252,434,99708,11,12,13,13,[O:1]([C:4]([O:2][O:3])([H:5])[H:6])[H:7].[C:8...
1,494257,439,79845,29,30,31,31,[O:1]([C:4]([O:2][O:3])([H:5])[H:6])[H:7].[C:8...

Contains 167200 rows

In [7]:
def read_column(name: str):
    table = pa.concat_tables(
        [
            pq.read_table(
                paquets / f"semiempirical_ts_semiempirical_{case}.parquet",
                columns=[name],
            )
            for case in ["v9", "nho_oho_1_v9", "nho_oho_2_v9", "nho_oho_3_v9"]
        ]
    )[name]
    return table

In [8]:
normal_termination = read_column("normal_termination")
keep_index = np.zeros(len(normal_termination), dtype=bool)
keep_index[matching_df["semiempirical_index"].values] = True
keep_index = np.logical_and(keep_index, normal_termination.to_pylist())
row_filter = pa.array(keep_index)
sum(keep_index).item(), row_filter.sum().as_py()

(167200, 167200)

In [9]:
column_metadata = {
    "smiles": "Reaction SMILES (with atom mapping indicating xyz and force order)",
    "route_section": "Level of theory",
    "charge": "Molecular formal charge",
    "multiplicity": "Electron multiplicity",
    "max_steps": "Maximum allowed steps",
    "cpu_time": "CPU time in seconds",
    "wall_time": "Wall time in seconds",
    "e0_h": "Enthalpy at 298K",
    "hf": "E0 for non-wavefunction methods",
    "zpe_per_atom": "Per-atom zero point energy",
    "e0_zpe": "Gibbs free energy at 0K",
    "gibbs": "Gibbs free energy at 298K",
    "frequencies": "Vibrational frequencies",
    "frequency_modes": "Vibrational modes",
    "initial_xyz": "Input XYZ coords",
    "std_xyz": "Standardized XYZ coords after optimization",
    "std_forces": "Standardized forces after optimization",
}

In [10]:
semiempirical_data = pa.Table.from_arrays(
    [pa.array(matching_df["smiles"])],
    schema=pa.schema([pa.field("smiles", pa.string())], metadata=column_metadata),
)

pbar = tqdm([key for key in column_metadata.keys() if key != "smiles"])
for name in pbar:
    pbar.set_description(f"Processing column {name}")
    column = read_column(name).filter(row_filter)
    if name in ["std_xyz", "std_forces"]:
        column = pa.array([extract_last(item.as_py()) for item in column])
    old_semiempirical_data = semiempirical_data
    semiempirical_data = old_semiempirical_data.append_column(name, column)
    del old_semiempirical_data
    del column

  0%|          | 0/16 [00:00<?, ?it/s]

In [11]:
semiempirical_data.schema

smiles: string
route_section: string
charge: uint8
multiplicity: uint8
max_steps: uint32
cpu_time: uint32
wall_time: uint32
e0_h: double
hf: double
zpe_per_atom: double
e0_zpe: double
gibbs: double
frequencies: list<element: double>
  child 0, element: double
frequency_modes: list<element: list<element: list<element: double>>>
  child 0, element: list<element: list<element: double>>
      child 0, element: list<element: double>
          child 0, element: double
initial_xyz: list<element: list<element: float>>
  child 0, element: list<element: float>
      child 0, element: float
std_xyz: list<item: list<item: double>>
  child 0, item: list<item: double>
      child 0, item: double
std_forces: list<item: list<item: double>>
  child 0, item: list<item: double>
      child 0, item: double
-- schema metadata --
smiles: 'Reaction SMILES (with atom mapping indicating xyz and force orde' + 2
route_section: 'Level of theory'
charge: 'Molecular formal charge'
multiplicity: 'Electron multiplicity'
max_steps: 'Maximum allowed steps'
cpu_time: 'CPU time in seconds'
wall_time: 'Wall time in seconds'
e0_h: 'Enthalpy at 298K'
hf: 'E0 for non-wavefunction methods'
zpe_per_atom: 'Per-atom zero point energy'
e0_zpe: 'Gibbs free energy at 0K'
gibbs: 'Gibbs free energy at 298K'
frequencies: 'Vibrational frequencies'
frequency_modes: 'Vibrational modes'
initial_xyz: 'Input XYZ coords'
std_xyz: 'Standardized XYZ coords after optimization'
std_forces: 'Standardized forces after optimization'

In [12]:
semiempirical_df = semiempirical_data.to_pandas()
head(semiempirical_df)

,smiles,route_section,charge,multiplicity,max_steps,cpu_time,wall_time,e0_h,hf,zpe_per_atom,e0_zpe,gibbs,frequencies,frequency_modes,initial_xyz,std_xyz,std_forces
0,[O:1]([C:4]([O:2][O:3])([H:5])[H:6])[H:7].[C:8...,"P opt=(ts,calcall,maxcycle=90,noeig,nomicro,ca...",0.0,2.0,90.0,57,9,-42.513596,-42.696474,0.169243,-42.527231,-42.568551,"[-781.8643, 32.471, 50.5414, 60.661, 91.1673, ...","[[[1.0, 8.0, -0.0, 0.0, -0.0], [2.0, 8.0, 0.02...","[[1.0, 8.0, 0.0, -1.794081, -1.656718, -0.0569...","[[1.0, 8.0, 0.0, -2.1198270320892334, -0.47277...","[[1.0, 8.0, 3.769999921132694e-07, 1.641000039..."
1,[O:1]([C:4]([O:2][O:3])([H:5])[H:6])[H:7].[C:8...,"P opt=(ts,calcall,maxcycle=90,noeig,nomicro,ca...",0.0,2.0,90.0,153,23,-43.551291,-43.750695,0.182283,-43.568411,-43.617631,"[-988.7339, 17.3197, 19.392, 30.6842, 41.6583,...","[[[1.0, 8.0, 0.0, -0.0, 0.0], [2.0, 8.0, 0.01,...","[[1.0, 8.0, 0.0, 0.000181, -0.076914, -0.82913...","[[1.0, 8.0, 0.0, -4.520959854125977, -1.711431...","[[1.0, 8.0, 6.419999749596172e-07, -3.69100007..."

Contains 167200 rows

In [13]:
rows_to_delete = set()
for col in semiempirical_df.columns:
    to_delete = semiempirical_df.index[semiempirical_df[col].isna()]
    rows_to_delete.update(to_delete)
    if len(to_delete) > 0:
        print(f"Column {col} has {len(to_delete)} missing values")

print(f"\nMarked {len(rows_to_delete)} rows for deletion")

Column charge has 1 missing values
Column multiplicity has 1 missing values
Column max_steps has 2 missing values
Column std_xyz has 2 missing values

Marked 4 rows for deletion

In [14]:
energy_cols = ["e0_h", "hf", "e0_zpe", "gibbs"]
mean_energy = semiempirical_df[energy_cols].mean(axis=1)
for col in energy_cols:
    deviations = (semiempirical_df[col] - mean_energy).abs()
    rows_to_delete.update(deviations.index[deviations > 1.0])

print(f"\nA total of {len(rows_to_delete)} rows are now marked for deletion.")

A total of 5 rows are now marked for deletion.

In [15]:
PARAMS = Chem.SmilesParserParams()
PARAMS.removeHs = False


def get_elements_from_smiles(smiles):
    reactant_smiles = smiles.split(">>")[0].split(".")
    mols = [Chem.MolFromSmiles(smi, PARAMS) for smi in reactant_smiles]
    order = {
        atom.GetAtomMapNum(): atom.GetSymbol()
        for mol in mols
        for atom in mol.GetAtoms()
    }
    try:
        return "".join([order[i] for i in range(1, len(order) + 1)])
    except TypeError:
        return ""


PERIODIC_TABLE = Chem.GetPeriodicTable()


def get_elements_from_xyz(xyz):
    if xyz is None:
        return None
    return "".join(PERIODIC_TABLE.GetElementSymbol(int(item[1])) for item in xyz)

In [16]:
elements_from_xyz = swifter_apply(
    semiempirical_df["std_xyz"], get_elements_from_xyz, "Getting elements from xyz"
)
elements_from_smiles = swifter_apply(
    semiempirical_df["smiles"],
    get_elements_from_smiles,
    "Getting elements from smiles",
)
rows_to_delete |= set(semiempirical_df.index[elements_from_smiles != elements_from_xyz])

print(f"\nA total of {len(rows_to_delete)} rows are now marked for deletion.")

Getting elements from xyz:   0%|          | 0/167200 [00:00<?, ?it/s]

Getting elements from smiles:   0%|          | 0/167200 [00:00<?, ?it/s]

A total of 37 rows are now marked for deletion.

In [17]:
keep_index = np.ones(len(semiempirical_df), dtype=bool)
keep_index[np.array(list(rows_to_delete), dtype=int)] = False
filtered_semiempirical_data = semiempirical_data.filter(pa.array(keep_index))
del semiempirical_data

In [18]:
data_dir.mkdir(parents=True, exist_ok=True)
pq.write_table(filtered_semiempirical_data, data_dir / output_file, compression="zstd")

In [19]:
parquet_file = pq.ParquetFile(data_dir / output_file)
print(f"Successfully wrote parquet file with {parquet_file.metadata.num_rows} rows")

Successfully wrote parquet file with 167163 rows