In [1]:
import pathlib

from functools import lru_cache

import pandas as pd
import swifter

from rdkit import Chem

In [ ]:
cwd = pathlib.Path().absolute()
QUANTUM_GREEN_DIR = pathlib.Path("/home/shared/projects/quantum_green")
PAPER_DIR = QUANTUM_GREEN_DIR / "paper" / "figure" / "section_3_1_2_ts_char"
DATABASE_DIR = cwd.parent.parent / "data" / "thermo"

In [3]:
pd.set_option("display.max_columns", None)


def head(df, n=2):
    display(df.head(n))
    print(f"Contains {len(df)} rows")


@lru_cache(maxsize=None)
def canonical_smiles(smiles):
    mol = Chem.MolFromSmiles(smiles)
    for atom in mol.GetAtoms():
        atom.SetAtomMapNum(0)
    return Chem.MolToSmiles(mol, isomericSmiles=True)


def clean_rxn_smi(rxn_smi):
    return ">>".join(
        [
            ".".join([canonical_smiles(smi) for smi in category.split(".")])
            for category in rxn_smi.split(">>")
        ]
    )


def get_rxn_smi(row):
    return row["r1smi"] + "." + row["r2smi"] + ">>" + row["p1smi"] + "." + row["p2smi"]

In [4]:
thermo_data = pd.read_pickle(
    PAPER_DIR / "quantum_green_ts_data_24july2c.pkl"
)
thermo_data["rxn_smi"] = thermo_data.swifter.apply(get_rxn_smi, axis=1)
head(thermo_data)

,ts_dft_log_source_utf_8_sha512,dft_table_id,ts_dft_log_path,ts_dft_route_section,charge,multiplicity,ts_dft_opt_max_steps,ts_dft_opt_normal_termination_check,ts_dft_opt_cpu_time,ts_dft_opt_wall_time,ts_dft_sum_of_electronic_and_thermal_enthalpies_hartree,ts_dft_hartreefock_energy_hartree,ts_dft_zpe_hartree,ts_dft_e0_zpe_hartree,ts_dft_gibbs_hartree,ts_dft_scf_hartree,ts_dft_frequency_modes,ts_dft_std_forces,ts_dft_opted_std_xyz,ts_dft_opted_xyz_input_orientation,is_ts,batch_label,ts_dft_log_filename_id,rsmi,psmi,r1smi,r2smi,p1smi,p2smi,r1nasmi,r2nasmi,p1nasmi,p2nasmi,std_xyz_str,xyz_str,p1_reaction_center_atom_map_num,r1_reaction_center_atom_map_num,h_atom_map_num,r1_matched_sha512,r2_matched_sha512,p1_matched_sha512,p2_matched_sha512,r1_matched_smi,r1_matched_std_xyz_str,r2_matched_smi,r2_matched_std_xyz_str,p1_matched_smi,p1_matched_std_xyz_str,p2_matched_smi,p2_matched_std_xyz_str,connectivity_check_r1,connectivity_check_r2,connectivity_check_r1_dist,connectivity_check_r2_dist,r2_h_idx,r2_reacting_site_idx,r2_reacting_site_element,r2_reacting_site_h_bond_distance,r2_ts_reacting_site_h_bond_distance,r2_ts_reacting_site_h_bond_distance_pct_change,connectivity_check_p1,connectivity_check_p2,connectivity_check_p1_dist,connectivity_check_p2_dist,p2_h_idx,p2_reacting_site_idx,p2_reacting_site_element,p2_reacting_site_h_bond_distance,p2_ts_reacting_site_h_bond_distance,p2_ts_reacting_site_h_bond_distance_pct_change,rxn_smi,fingerprint,rxn_smi_original_order,rdmc_large_factor,rdmc_small_factor,neg_freq,neg_freq_z_score,rp_connectivity_check_true_sum,connectivity_check_r1_score,connectivity_check_r2_score,connectivity_check_p2_score,connectivity_check_p1_score,ho2_ts_h_mode,ho2_non_react_h_mode,ho2_ts_h_score,ho2_non_react_h_score,ho2_non_div_ts_mode_ratio,r1_dft_e0_zpe_hartree,r2_dft_e0_zpe_hartree,p1_dft_e0_zpe_hartree,p2_dft_e0_zpe_hartree,rcomplex_dft_e0_zpe_hartree,pcomplex_dft_e0_zpe_hartree,dft_fwd_barrier_e0_zpe_hartree,dft_rev_barrier_e0_zpe_hartree,dft_fwd_Hrxn_e0_zpe_hartree,dft_fwd_barrier_e0_zpe_kcal,dft_rev_barrier_e0_zpe_kcal,dft_fwd_Hrxn_e0_zpe_kcal,ts_dlpno_log_filename_id,ts_dlpno_xyz_tuple,ts_dlpno_log_path,ts_dlpno_sp_hartree,dft_opted_xyz_tuple_used_for_dlpno_calc,r1_dlpno_sp_hartree,r2_dlpno_sp_hartree,p1_dlpno_sp_hartree,p2_dlpno_sp_hartree,all_species_has_dlpno_sp,fwd_Hrxn_dlpno_sp_hartree,ts_and_species_has_dlpno_sp,fwd_barrier_dlpno_sp_hartree,rev_barrier_dlpno_sp_hartree,fwd_Hrxn_dlpno_sp_kcal,fwd_barrier_dlpno_sp_kcal,rev_barrier_dlpno_sp_kcal,r1_dft_log_path,r2_dft_log_path,p1_dft_log_path,p2_dft_log_path,r1_dlpno_log_path,r2_dlpno_log_path,p1_dlpno_log_path,p2_dlpno_log_path,r1_dft_hartreefock_energy_hartree,r2_dft_hartreefock_energy_hartree,p1_dft_hartreefock_energy_hartree,p2_dft_hartreefock_energy_hartree,r1_dft_zpe_hartree,r2_dft_zpe_hartree,p1_dft_zpe_hartree,p2_dft_zpe_hartree,ts_and_species_has_dft_zpe,species_has_dft_zpe,fwd_Hrxn_dft_zpe_hartree,fwd_barrier_dft_zpe_hartree,rev_barrier_dft_zpe_hartree,fwd_Hrxn_dlpno_sp_dft_zpe_hartree,fwd_barrier_dlpno_sp_dft_zpe_hartree,rev_barrier_dlpno_sp_dft_zpe_hartree,fwd_Hrxn_dlpno_sp_dft_zpe_kcal,fwd_barrier_dlpno_sp_dft_zpe_kcal,rev_barrier_dlpno_sp_dft_zpe_kcal,r1_dft_zpe_scaled_hartree,r2_dft_zpe_scaled_hartree,p1_dft_zpe_scaled_hartree,p2_dft_zpe_scaled_hartree,ts_dft_zpe_scaled_hartree,fwd_barrier_dlpno_sp_dft_zpe_scaled_hartree,rev_barrier_dlpno_sp_dft_zpe_scaled_hartree,fwd_Hrxn_dlpno_sp_dft_zpe_scaled_hartree,rev_Hrxn_dlpno_sp_dft_zpe_scaled_hartree,fwd_barrier_dlpno_sp_dft_zpe_scaled_kcal,rev_barrier_dlpno_sp_dft_zpe_scaled_kcal,fwd_Hrxn_dlpno_sp_dft_zpe_scaled_kcal,rev_Hrxn_dlpno_sp_dft_zpe_scaled_kcal,ts_dft_frequencies,r1_dft_frequencies,r2_dft_frequencies,p1_dft_frequencies,p2_dft_frequencies,smiles
0,4c648a435eb66f655a9afa7aebe1b6288cfbe5d4377ab7...,545983,/home/gridsan/groups/RMG/Projects/Habs/data/ts...,"P opt=(ts,calcall,maxcycle=64,noeig,nomicro,ca...",0,2,64,True,53637.5,1178.8,-499.312919,-499.513846,0.187656,-499.326190,-499.365824,499.513846,"[[[1.0, 8.0, -0.01, 0.0, -0.03], [2.0, 8.0, 0....","[[1.0, 8.0, 2.5425e-05, -7.272e-06, -2.4919e-0...","[[1.0, 8.0, 0.0, -0.296608, 2.50034, -0.42834]...","[[1.0, 8.0, 0.0, -0.07876, -1.01869, -0.072806...",True,oo_g4mp2,2584189,[O:1]([O:2])[H:3].[C:4]1([C:5]([C:8]([C:10](=[...,[C:4]1([C:5]([C:8]([C:10](=[O:22])[H:23])([H:1...,[O:1]([O:2])[H:3],[C:4]1([C:5]([C:8]([C:10](=[O:22])[H:23])([H:1...,[C:4]1([C:5]([C:8]([C:10](=[O:22])[H:23])([H:1...,[O:1]([O:2][H:11])[H:3],[O]O,CC(CC=O)C1CC1,C[C](CC=O)C1CC1,OO,23\n\nO -0.296608 2.50034 -0.42834\nO 0.12862 ...,23\n\nO -0.07876 -1.01869 -0.072806\nO 0.9303 ...,5,2,11,d1ca3ead22026cd95cd9eba36a347437a7d6f6adab5c4b...,610ba260b0107be2c50383d2bf26bf5fc5467c7ad8288b...,0a477b232ce026d015e750e1199a52b816a5fd4e81b88d...,a378723d20b8e233b8c52a4a265f23e51eed6de0c99f59...,[O:1][O:2][H:3],3\n\nO 0.055113 0.705073 0.0\nO 0.055113 -0.59...,[C:1]([C:2]([C:3]([C:4](=[O:5])[H:15])([H:13])...,20\n\nC 0.216362 1.782055 0.054566\nC -0.13150...,[C:1]([C:2]([C:3]([C:4](=[O:5])[H:14])([H:12])...,19\n\nC -0.008753 1.669215 -0.212931\nC 0.0510...,[O:1]([O:2][H:4])[H:3],4\n\nO 0.0 0.708624 -0.054351\nO -0.0 -0.70862...,True,True,[0.05700816 0.05700816 0.00748912 0.00748912],[0.00946447 0.00248608 0.00129841 0.00037547 0...,11,1,C,1.106773,1.312754,0.156907,True,True,[1.36928176e-02 2.58629462e-03 6.66837529e-03 ...,[0.02934109 0.00283253 0.02934109 0.00283253],3,1,O,0.965842,1.209684,0.201575,[O:1]([O:2])[H:3].[C:4]1([C:5]([C:8]([C:10](=[...,45ff0c52c5e6de887c3d5db1a3d4530d,[C:4]1([C:5]([C:8]([C:10](=[O:22])[H:23])([H:1...,13.648967,0.0,-1819.2074,-0.180464,4,0.218532,0.013364,0.057661,0.029017,"[11.0, 1.0, 0.05, 0.99, 0.03]","[1.0, 8.0, -0.01, 0.0, -0.03]",0.991716,0.031623,0.031887,-150.721953,-348.624311,-347.977987,-151.349014,-499.346264,-499.327001,0.020074,0.000811,0.019263,12.596625,0.508910,12.087715,id54674,"((-0.07876, -1.01869, -0.072806), (0.9303, -0....",/home/gridsan/jburns/RMG_shared/Projects/Hao-W...,-499.420713,"((-0.07876, -1.01869, -0.072806), (0.9303, -0....",-150.773531,-348.675816,-348.013214,-151.4225,True,0.013633,True,0.028633,0.015001,8.554567,17.967630,9.413063,/home/gridsan/groups/RMG/Projects/Hao-Wei-Osca...,/home/gridsan/groups/RMG/Projects/Hao-Wei-Osca...,/home/gridsan/groups/RMG/Projects/Hao-Wei-Osca...,/home/gridsan/groups/RMG/Projects/Hao-Wei-Osca...,/home/gridsan/jburns/RMG_shared/Projects/Hao-W...,/home/gridsan/jburns/RMG_shared/Projects/Hao-W...,/home/gridsan/jburns/RMG_shared/Projects/Hao-W...,/home/gridsan/jburns/RMG_shared/Projects/Hao-W...,-150.736553,-348.800739,-348.140437,-151.376196,0.0146,0.176428,0.16245,0.027182,True,True,-0.001396,-0.003372,-0.001976,0.012236,0.025261,0.013025,7.678501,15.851793,8.173292,0.014197,0.171556,0.157964,0.026431,0.182474,0.025355,0.01308,0.012275,-0.012275,15.910219,8.207526,7.702692,-7.702692,"[-1819.2074, 54.014, 69.9409, 78.7383, 95.0168...","[1268.6637, 1466.9774, 3673.0462]","[54.4468, 75.2434, 102.0769, 166.2486, 229.237...","[38.6623, 46.6427, 70.6254, 124.3627, 195.2907...","[355.51, 1029.1913, 1349.894, 1491.2134, 3851....",[O:1]([O:2])[H:3].[C:4]1([C:5]([C:8]([C:10](=[...
1,3fcdf61497a20d2e765655162f9a50bd8067a6ae90e90e...,545984,/home/gridsan/groups/RMG/Projects/Habs/data/ts...,"P opt=(ts,calcall,maxcycle=64,noeig,nomicro,ca...",0,2,64,True,87382.4,1915.1,-575.604651,-575.835651,0.216399,-575.619252,-575.662671,575.835651,"[[[1.0, 8.0, 0.02, 0.01, -0.01], [2.0, 8.0, -0...","[[1.0, 8.0, -6.29e-07, -8.11e-07, 6.03e-07], [...","[[1.0, 8.0, 0.0, 2.669129, -1.916241, 0.102074...","[[1.0, 8.0, 0.0, 2.900762, 1.051554, -2.878215...",True,oo_g4mp2,2759514,[O:1]([O:2])[H:3].[C:4]1([O:11][C:5]([C:8]([O:...,[C:4]1([O:11][C:5]([C:8]([O:12][C:10]([H:25])[...,[O:1]([O:2])[H:3],[C:4]1([O:11][C:5]([C:8]([O:12][C:10]([H:24])(...,[C:4]1([O:11][C:5]([C:8]([O:12][C:10]([H:25])[...,[O:1]([O:2][H:24])[H:3],[O]O,COCC(C)OC1CC1,[CH2]OCC(C)OC1CC1,OO,26\n\nO 2.669129 -1.916241 0.102074\nO 3.62579...,26\n\nO 2.900762 1.051554 -2.878215\nO 3.37906...,10,2,24,d1ca3ead22026cd95cd9eba36a347437a7d6f6adab5c4b...,09d7101d699a76511a92cf2607786664c9f074ee20a378...,36ef1974554666d88c201c7fd525e42cbdfc9e88e4f93e...,a378723d20b8e233b8c52a4a265f23e51eed6de0c99f59...,[O:1][O:2][H:3],3\n\nO 0.055113 0.705073 0.0\nO 0.055113 -0.59...,[C:1]([O:2][C:3]([C:4]([C:5]([H:16])([H:17])[H...,23\n\nC 2.355263 -1.592675 0.183484\nO 2.52464...,[C:1]([O:2][C:3]([C:4]([C:5]([H:15])([H:16])[H...,22\n\nC 1.79229 -1.9024 0.57597\nO 1.564071 -1...,[O:1]([O:2][H:4])[H:3],4\n\nO 0.0 0.708624 -0.054351\nO -0.0 -0.70862...,True,True,[0.05822702 0.05822702 0.00820458 0.00820458],[3.06791240e-02 3.36613486e-03 3.69001136e-03 ...,9,0,C,1.099011,1.332498,0.175225,True,True,[0.00805211 0.00649287 0.00520663 0.00805211 0...,[0.02822179 0.00210964 0.02822179 0.00210964],3,1,O,0.965842,1.200348,0.195365,[O:1]([O:2])[H:3].[C:4]1([O:11][C:5]([C:8]([O:...,fe6f921ca72c34388a0ece88ef9c4bf1,[C:4]1([O:11][C:5]([C:8]([O:12][C:10]([H:24])(...,15.512329,0.0,-1780.9655,0.010284,4,0.228270,0.069623,0.053246,0.010703,"[24.0, 1.0, -0.34, 0.92, 0.13]","[1.0, 8.0, 0.02, 0.01, -0.01]",0.989394,0.024495,0.024757,-150.721953,-424.919453,-424.271413,-151.349014,-575.641406,-575.620427,0.022154,0.001175,0.020979,13.901845,0.737324,13.164521,id55203,"((2.900762, 1.051554, -2.878215), (3.379065, 0...",/home/gridsan/jburns/RMG_shared/Projects/Hao-W...,-575.755980,"((2.900762, 1.051554, -2.878215), (3.379065, 0...",-150.773531,-425.012518,-424.350164,-151.4225,True,0.013386,True,0.030069,0.016683,8.399621,18.868576,10.468954,/home/gridsan/groups/RMG/Projects/Hao-Wei-Osca...,/home/gridsan/groups/RMG/Projects/Hao-Wei-Osca...,/home/gridsan/groups/RMG/Projects/Hao-Wei-Osca...,/home/gridsan/groups/RMG/Projects/Hao-Wei-Osca...,/home/gridsan/jburns/RMG_shared/Projects/Hao-W...,/home/gridsan/jburns/RMG_shared/Projects/Hao-W...,/home/gridsan/jburns/RMG_shared/Projects/Hao-W...,/home/gridsan/jburns/RMG_shared/Projects/Hao-W...,-150.736553,-425.124273,-424.462568,-151.376196,0.0146,0.204819,0.191155,0.027182,True,True,-0.001083,-0.003021,-0.001938,0.012303,0.027048,0.014746,7.720091,16.973058,9.252967,0.014197,0.199164,0.185876,0.026431,0.210423,0.027132,0.014799,0.012333,-0.012333,17.0254,9.286544,7.738855,-7.738855,"[-1780.9655, 22.7631, 39.1821, 48.2943, 53.310...","[1268.6637, 1466.9774, 3673.0462]","[41.7173, 46.7835, 79.0284, 116.919, 165.6573,...","[41.6898, 69.9592, 110.6483, 138.1279, 181.957...","[355.51, 1029.1913, 1349.894, 1491.2134, 3851....",[O:1]([O:2])[H:3].[C:4]1([O:11][C:5]([C:8]([O:...

Contains 167237 rows

In [5]:
thermo_data["clean_rxn_smi"] = thermo_data["rxn_smi"].swifter.apply(clean_rxn_smi)

Pandas Apply:   0%|          | 0/167237 [00:00<?, ?it/s]

In [6]:
thermo_df = pd.DataFrame(
    {
        "rxn_smi": thermo_data["clean_rxn_smi"],
        "dlpno_sp_hartree": thermo_data["ts_dlpno_sp_hartree"],
        "dft_zpe_scaled_hartree": 0.9723865877712031
        * thermo_data["ts_dft_zpe_hartree"],
    }
)
head(thermo_df)

,rxn_smi,dlpno_sp_hartree,dft_zpe_scaled_hartree
0,[O]O.CC(CC=O)C1CC1>>C[C](CC=O)C1CC1.OO,-499.420713,0.182474
1,[O]O.COCC(C)OC1CC1>>[CH2]OCC(C)OC1CC1.OO,-575.755980,0.210423

Contains 167237 rows

In [7]:
delta = thermo_df["dft_zpe_scaled_hartree"] - thermo_data["ts_dft_zpe_scaled_hartree"]
delta.min(), delta.max()

(np.float64(0.0), np.float64(0.0))

Looking for duplicates

In [8]:
thermo_df[thermo_df["rxn_smi"].duplicated(keep=False)].sort_values(by="rxn_smi")

,rxn_smi,dlpno_sp_hartree,dft_zpe_scaled_hartree
24695,[O]O.CCCc1nc(C)c[nH]1>>C[CH]Cc1nc(C)c[nH]1.OO,-533.687075,0.190482
60097,[O]O.CCCc1nc(C)c[nH]1>>C[CH]Cc1nc(C)c[nH]1.OO,-533.686479,0.190482
1827,[O]O.Cc1[nH]cnc1C=O>>Cc1[nH]cnc1[C]=O.OO,-529.132458,0.119058
29769,[O]O.Cc1[nH]cnc1C=O>>Cc1[nH]cnc1[C]=O.OO,-529.132837,0.119058
27394,[O]O.Cc1cc(C=O)n[nH]1>>Cc1cc([C]=O)n[nH]1.OO,-529.109163,0.118688
53602,[O]O.Cc1cc(C=O)n[nH]1>>Cc1cc([C]=O)n[nH]1.OO,-529.107864,0.118127
118423,[O]O.c1cc(C2CC2)n[nH]1>>C1=CC(C2CC2)=N[N]1.OO,-493.155124,0.140986
121220,[O]O.c1cc(C2CC2)n[nH]1>>C1=CC(C2CC2)=N[N]1.OO,-493.154929,0.140986

In [9]:
thermo_df_no_duplicates = thermo_df.drop_duplicates(subset="rxn_smi", keep=False)

In [10]:
thermo_df_no_duplicates.to_csv(
    DATABASE_DIR / "quantumpioneer_thermo_dataset_transition_states.csv", index=False
)